name: 'Setup Docker'
description: 'Setup Docker for testing'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Start Docker services
      run: |
        # Add any Docker setup commands here if needed
        echo "Docker setup complete"
      shell: bash
