#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged (ESLint and Prettier)
echo "🔍 Running lint-staged (ESLint and Prettier)..."
npx lint-staged

# Run all tests
echo "🧪 Running all tests..."
npm test
