name: build

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ main, staging ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: production
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-npm
      - uses: ./.github/actions/install-dependencies
      - uses: ./.github/actions/run-command
        with:
          name: build project
          command: npm run build:ci
