name: server tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  server-tests:
    name: server tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-npm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/setup-docker

      - name: run server tests with coverage
        run: npm run test:coverage -- --testPathPattern=services
        env:
          CI: true
