name: type checking

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  type-check:
    name: type check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-npm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/run-command
        with:
          name: run type checking
          command: npm run typecheck
